name: Waka Readme

on:
  schedule:
    # 国际标准时间下午 16 点，北京时间晚上 0 点
    - cron: '0 16 * * *'
    
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE : "True"
          SHOW_PROFILE_VIEWS : "True"
          SHOW_LANGUAGE_PER_REPO : "True"
          SHOW_LOC_CHART : "True"
          SHOW_SHORT_INFO : "True"
          SHOW_PROJECTS : "True"
          SHOW_TOTAL_CODE_TIME : "True"
